[package]
name = "resizer-stamina-add-on"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
fromsoftware-shared.workspace = true
eldenring.workspace = true
serde.workspace = true
toml.workspace = true
windows = { workspace = true, features = ["Win32_System_LibraryLoader"] }

[lib]
name = "resizer_stamina_add_on"
crate-type = ["cdylib"]
